### ISSUE TITLE
优先级高 elementIdClear()、elementIdValue()、elementIdText()、elementIdCssProperty() 不能正常执行

### ISSUE THREAD

**Issue by lol666666** [web-driverify/web-driverify#10]
常用的这些API 优先级较高，elementIdClear()、elementIdValue()、elementIdText()、elementIdCssProperty() 不能正常执行

**Comment by harttle** [comment]
elementIdValue(), elementIdClear() 已支持，发现 bug 令提 Issue。这两个 API 测试是 Pass 的：

https://github.com/web-driverify/web-driverify/blob/master/test/e2e/element-interaction.js#L35-L40

elementIdText() 也是 Pass 的，参考：

https://github.com/web-driverify/web-driverify/blob/master/test/e2e/element-state.js#L17-L20

elementIdCssProperty() 待开发。

**Comment by harttle** [comment]
elementIDCSSProperty已支持，@1.1.0
