### ISSUE TITLE
优先级高，browser.getSource(); browser.getHTML(selector[,includeSelectorTag]);

### ISSUE THREAD

**Issue by lol666666** [web-driverify/web-driverify#12]

**Comment by harttle** [comment]
我会实现这两个 API，但 getSource 和 getHTML 会占不小内存和带宽（对baidu结果页应该是 M 级别）。不推荐使用

**Comment by harttle** [comment]
.getHTML 不需要 web-driverify 实现。注意查看 webdriverIO 使用的到底是哪个 WebDriver Protocol API。这个例子中，要实现的 API 是 selectorExecute()

**Comment by lol666666** [comment]
:)OO,SOSO
