### ISSUE TITLE
the way to make input has focus(executing the js way to have focus can not run)

### ISSUE THREAD

**Issue by JiangtaoPei** [web-driverify/web-driverify#13]
to verify the sug and his case.

**Comment by harttle** [comment]
I did'nt find set focus related API from [WebDriver Protocol][wd]. It seems that [Element Click][elclick] is the way to trigger focus, but not implemented correctly by now.

[wd]: https://www.w3.org/TR/webdriver/
[elclick]: https://www.w3.org/TR/webdriver/#element-click

**Comment by harttle** [comment]
now element click triggers touch event in @1.1.1
