### ISSUE TITLE
webserver 支持case的并发执行

### ISSUE THREAD

**Issue by lol666666** [web-driverify/web-driverify#2]
**建议全部由一个server支持，因为手机host的端口号，需要根据对应server的端口绑定**
**使用场景：**
(1).不同的手机并发执行不同的测试用例，用同一个server运行，并正确输出对应手机当前并行case的结果或报告。
(2).同一个手机，同一个server运行，队列执行case分组任务，并行case的结果信息不混乱
(3).**优先级队列实现：**
     1.当前执行一组任务A，同时紧急case任务B触发，安全退出当前case任务A，执行紧急任务B，执行B完毕后，继续执行任务A，任务A和任务B的case结果和报告输出正确

**Comment by harttle** [comment]
服务器并发是by design的，该问题是由于 rmtc 插件不支持客户端配置。现已更新 rmtc 与相应框架 plugin 配置机制，closing
