### ISSUE TITLE
支持通过Parent element，获取到child element的数量和个数，并可以遍历获取child element（color、value、attribute等信息）

### ISSUE THREAD

**Issue by lol666666** [web-driverify/web-driverify#3]
1).使用场景：例如首页10条结果，获取其中任意第几条结果或获取的详细信息（title，摘要等）：
(2).获取当前结果页的全部结果数

![image](https://user-images.githubusercontent.com/10813359/31450193-635b6252-aedb-11e7-9d9b-2fc7166c9deb.png)

**Comment by harttle** [comment]
Issue 请提供具体缺失哪个 API，或者哪个 API 有 Bug。WebDriver Protocol API 不可满足的部分，使用 execute API 来插入脚本执行。Closing
